name: Vanilla OS for Zenbook Duo # Replace this name with your image name
id: zenbookduovanilla # Replace this ID with your image ID
stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:main # Optionally, Replace this image URL with a different one i.e. nvidia:main, etc
  singlelayer: false
  labels:
    maintainer: self-maintained # Optionally, Replace this with your name
  args:
    DEBIAN_FRONTEND: noninteractive # Set the image environment as non-interactive
  
  # Commands to run first before building the modules
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: init-setup
    type: shell
    commands:
    - lpkg --unlock
    - apt-get update

  # Put your custom actions below this comment

  # - name: example-packages # Sample module using the built-in Apt module to install packages
  #   type: apt
  #   source:
  #     packages:
  #     - vim

  - name: install tailscale # Sample module demonstrating the Shell module with custom commands
    type: shell
    commands:
    - curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg | tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
    - curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.tailscale-keyring.list | tee /etc/apt/sources.list.d/tailscale.list
    - apt-get update
    - apt-get install tailscale -y
  
  - name: change bgrt # Sample module demonstrating the Shell module with custom commands
    type: shell
    commands:
    - plymouth-set-default-theme -R bgrt

  - name: asus-wmi-screenpad
    type: shell
    commands:
    - apt install dkms -y # Should already be installed, just making sure.
    - mkdir /usr/src/asus-wmi-1.0
    - cd /usr/src/asus-wmi-1.0
    - wget 'https://github.com/Plippo/asus-wmi-screenpad/archive/master.zip'
    - unzip master.zip
    - mv asus-wmi-screenpad-master/* .
    - rmdir asus-wmi-screenpad-master
    - rm master.zip
    - sed -i "2s/.*/VERSION=`cat /usr/share/vanilla/kernel-version | grep -o '^[0-9]\+\.[0-9]\+'`/" prepare-for-current-kernel.sh # Make sure it wont prepare the wrong kernel
    - sh prepare-for-current-kernel.sh
    - echo Using kernel -k $(cat /usr/share/vanilla/kernel-version)
    - dkms add -m asus-wmi -v 1.0 -k $(cat /usr/share/vanilla/kernel-version)
    - dkms build -m asus-wmi -v 1.0 -k $(cat /usr/share/vanilla/kernel-version)
    - dkms install -m asus-wmi -v 1.0 -k $(cat /usr/share/vanilla/kernel-version)
    - chmod a+w '/sys/class/leds/asus::screenpad/brightness'
  
  # Put your custom actions above this comment

  - name: set-image-name-abroot
    type: includes
    includes:
      - modules/80-set-image-abroot-config.yml

  - name: cleanup
    type: shell
    commands:
    - apt-get autoremove -y
    - apt-get clean
    - lpkg --lock

  - name: fsguard
    type: fsguard
    CustomFsGuard: false
    FsGuardLocation: "/usr/sbin/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]
    modules:
      - name: remove-prev-fsguard
        type: shell
        commands:
          - rm -rf /FsGuard 
          - rm -f ./minisign.pub ./minisign.key 
          - chmod +x /usr/sbin/init

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
